# Generated by Django 3.2.3 on 2021-06-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('car_position', models.IntegerField(verbose_name='Позиция автомобиля')),
                ('car_color', models.CharField(max_length=30, verbose_name='Цвета')),
                ('car_date', models.IntegerField(verbose_name='Год выпуска')),
                ('car_vin', models.CharField(max_length=17, verbose_name='Идт. Авто')),
                ('car_status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'База машин',
                'verbose_name_plural': 'База машин',
            },
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('car_colors', models.CharField(max_length=250, verbose_name='Цвета')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('full_text', models.TextField(verbose_name='Полная описание')),
            ],
            options={
                'verbose_name': 'Инф. авто',
                'verbose_name_plural': 'Инф. авто',
            },
        ),
        migrations.CreateModel(
            name='CarOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vend_id', models.IntegerField(verbose_name='Id Продовца')),
                ('cust_id', models.IntegerField(verbose_name='Id Покупателья')),
                ('car_name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('car_color', models.CharField(max_length=30, verbose_name='Цвет авто')),
                ('car_position', models.IntegerField(verbose_name='Позиция авто')),
                ('car_year', models.IntegerField(verbose_name='Год выпуска')),
                ('payment', models.CharField(max_length=30, verbose_name='Вид оплаты')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='CarSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('car_position', models.IntegerField(verbose_name='Позиция автомобиля')),
                ('car_summ', models.IntegerField(verbose_name='Стоимость авто')),
            ],
            options={
                'verbose_name': 'Сумма',
                'verbose_name_plural': 'Сумма',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=30, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('phone1', models.CharField(max_length=13, verbose_name='Телефон номер 1')),
                ('phone2', models.CharField(max_length=13, verbose_name='Телефон номер 2')),
                ('email', models.EmailField(max_length=250, verbose_name='Е-майл')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vend_id', models.IntegerField(verbose_name='Id Продовца')),
                ('cust_id', models.IntegerField(verbose_name='Id Покупателья')),
                ('car_vin', models.CharField(max_length=17, verbose_name='Идт. Авто')),
                ('sales_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('sales_sum', models.IntegerField(verbose_name='Сумма продажи')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон номер')),
                ('email', models.EmailField(max_length=250, verbose_name='Е-майл')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Продовец',
                'verbose_name_plural': 'Продавции авто',
            },
        ),
    ]
