# Generated by Django 3.2.3 on 2021-06-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0002_auto_20210605_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, max_length=13, verbose_name='Телефон номер 2'),
        ),
    ]
