# Generated by Django 3.2.3 on 2021-06-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0003_alter_customer_phone2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOrder2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('cust_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('cust_phone', models.CharField(max_length=13, verbose_name='Телефон номер')),
                ('car_name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('car_color', models.CharField(max_length=30, verbose_name='Цвет авто')),
                ('car_position', models.IntegerField(verbose_name='Позиция авто')),
                ('car_year', models.IntegerField(verbose_name='Год выпуска')),
                ('payment', models.CharField(max_length=30, verbose_name='Вид оплаты')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='SalesInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30, verbose_name='Наименование')),
                ('sales_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('sales_sum', models.IntegerField(verbose_name='Сумма продажи')),
                ('car_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='staffer.carcategory', verbose_name='Типы авто')),
            ],
        ),
        migrations.DeleteModel(
            name='CarOrder',
        ),
        migrations.DeleteModel(
            name='SalesInfo',
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='фото авто'),
        ),
    ]
